In [1]:
import math

math.sqrt(25)

5.0

In [2]:
math.pi

3.141592653589793

In [3]:
import math as mt
import numpy

In [4]:
stats from scipy

SyntaxError: invalid syntax (<ipython-input-4-924452bf43bd>, line 1)

In [1]:
from scipy import stats

ImportError: DLL load failed: The network path was not found.

In [43]:
from numpy import random
import numpy as np

# uniform random numbers in [0,1]
dataOne = random.rand(5,5)
print(dataOne)

[[0.74743049 0.86917425 0.69205313 0.55783861 0.9398812 ]
 [0.74295973 0.2757784  0.51112781 0.14921815 0.11059416]
 [0.07435152 0.19699131 0.28374041 0.87600992 0.64517761]
 [0.45515392 0.22769954 0.10731263 0.15533262 0.85381346]
 [0.65639373 0.76927288 0.4918381  0.3979893  0.78115529]]


In [7]:
np.mean(dataOne)


0.5502294507559204

In [48]:
from scipy import stats


ImportError: DLL load failed: The network path was not found.

In [3]:
varOne = 25
varTwo = 25.0
varThree = varOne + varTwo
print(varThree)



50.0


In [7]:
varOne = 25
varTwo = ' Hello'
varThree = str(varOne) + varTwo
print(varThree)

#para concatenar numeros con texto es necesario convertir a string primero

25 Hello


In [12]:
# Dictionary Example
import math as mt
list = [44,22,33,11,55]
print(list[0])
# function #1
print(mt.factorial(list[0]))

# function #2
print(mt.isfinite(list[2]))

# function #3
print(mt.exp(list[3]))



44
2658271574788448768043625811014615890319638528000000000
True
59874.14171519782


In [2]:
import datetime

mydate = datetime.datetime.now()
print(mydate)

2019-08-30 22:01:12.363897


In [3]:
import math

def sum(var1, var2):
    var3 = var1 + var2
    print(var3)
    

sum(3, 9)

12


In [4]:
def DisplayMulti(*VarArgs): 
    for Arg in VarArgs: 
        if Arg.upper() == 'CONT': 
            continue 
            print('Continue Argument: ' + Arg) 
        elif Arg.upper() == 'BREAK': 
            break 
            print('Break Argument: ' + Arg) 
        print('Good Argument: ' + Arg)

DisplayMulti('Hello', 'Cont', 'Goodbye', 'Break', 'Last')


Good Argument: Hello
Good Argument: Goodbye


In [12]:
#NOTA: no hace falta importar sets en Python3 (from sets import Set )
SetA = set(['Red', 'Blue', 'Green', 'Black']) 
SetB = set(['Black', 'Green', 'Yellow', 'Orange']) 
SetX = SetA.union(SetB) 
SetY = SetA.intersection(SetB) 
SetZ = SetA.difference(SetB)

varStr = '{0}\n{1}\n{2}' 
print (varStr.format(SetX, SetY, SetZ) )


{'Red', 'Orange', 'Black', 'Yellow', 'Green', 'Blue'}
{'Black', 'Green'}
{'Red', 'Blue'}


In [13]:
ListA = [0, 1, 2, 3] 
ListB = [4, 5, 6, 7] 
ListA.extend(ListB) 
ListA


[0, 1, 2, 3, 4, 5, 6, 7]

In [18]:
MyTuple = (1, 2, 3, (4, 5, 6, (7, 8, 9)))

MyTuple.__add__((10, 11, 12, (13, 14, 15))) 

for Value1 in MyTuple: 
    if type(Value1) == int: 
        print (Value1)
    else: 
        for Value2 in Value1: 
            if type(Value2) == int: 
                print ("\t", Value2)
            else: 
                for Value3 in Value2: 
                    print ("\t\t", Value3)


1
2
3
	 4
	 5
	 6
		 7
		 8
		 9


In [22]:
ListA = ['Orange', 'Yellow', 'Green', 'Brown'] 
ListB = [1, 2, 3, 4]

for Value in ListB[1:3]: 
    print (Value)

    
for Value1, Value2 in zip(ListA, ListB): 
    print (Value1, '\t', Value2)


2
3
Orange 	 1
Yellow 	 2
Green 	 3
Brown 	 4


In [30]:
# Capitulo 5

with open("Colors.txt", 'r') as open_file: 
    print ('Colors.txt content:\n' + open_file.read())


Colors.txt content:
Color	Value
Red	1
Orange	2
Yellow	3
Green	4
Blue	5
Purple	6
Black	7
White	8


In [32]:
with open("Colors.txt", 'r') as open_file: 
    for observation in open_file: 
        print ('Reading Data: ' + observation)


Reading Data: Color	Value

Reading Data: Red	1

Reading Data: Orange	2

Reading Data: Yellow	3

Reading Data: Green	4

Reading Data: Blue	5

Reading Data: Purple	6

Reading Data: Black	7

Reading Data: White	8


In [33]:
n = 2 
with open("Colors.txt", 'r') as open_file: 
    for j, observation in enumerate(open_file): 
        if j % n==0: 
            print('Reading Line: ' + str(j) + 
            ' Content: ' + observation)
            


Reading Line: 0 Content: Color	Value

Reading Line: 2 Content: Orange	2

Reading Line: 4 Content: Green	4

Reading Line: 6 Content: Purple	6

Reading Line: 8 Content: White	8


In [34]:
from random import random 
sample_size = 0.25 
with open("Colors.txt", 'r') as open_file: 
    for j, observation in enumerate(open_file): 
        if random()<=sample_size: 
            print('Reading Line: ' + str(j) + 
            ' Content: ' + observation)


Reading Line: 0 Content: Color	Value

Reading Line: 1 Content: Red	1

Reading Line: 6 Content: Purple	6

Reading Line: 8 Content: White	8


In [36]:
import pandas as pd 
# Nota: read_table está desactualizado, mejor usar read_csv con el param sep='\t' 
# para archivos de texto con tabulaciones como separador
color_table = pd.io.parsers.read_csv("Colors.txt", sep='\t') 
print (color_table)



    Color  Value
0     Red      1
1  Orange      2
2  Yellow      3
3   Green      4
4    Blue      5
5  Purple      6
6   Black      7
7   White      8


In [38]:
import pandas as pd 
titanic = pd.io.parsers.read_csv("Titanic.csv") 
X = titanic[['age']] 
print(X)

        age
0   29.0000
1    0.9167
2    2.0000
3   30.0000
4   25.0000
5   48.0000
6   63.0000
7   39.0000
8   53.0000
9   71.0000
10  47.0000
11  18.0000
12  24.0000
13  26.0000
14  80.0000


In [2]:
from skimage.io import imread 
from skimage.transform import resize 
from matplotlib import pyplot as plt 
import matplotlib.cm as cm 

example_file = ("http://upload.wikimedia.org/" + 
    "wikipedia/commons/7/7d/Dog_face.png") 
image = imread(example_file, as_grey=True) 
plt.imshow(image, cmap=cm.gray) 
plt.show()


ImportError: DLL load failed: The network path was not found.